# Docker Compose pour le déploiement
version: '3.8'

services:
  website-builder:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
  # Optionnel : Nginx comme reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/certs  # Pour les certificats SSL
    depends_on:
      - website-builder
    restart: unless-stopped